VIA_ENABLE = no
LTO_ENABLE = yes
ENCODER_MAP_ENABLE = no

NKRO_ENABLE = yes           # Enable N-Key Rollover
BOOTMAGIC_ENABLE = no      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes        # Mouse keys
EXTRAKEY_ENABLE = no       # Audio control and System control
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no
DIP_SWITCH_ENABLE = no
RGB_MATRIX_ENABLE = no
COMBO_ENABLE = yes
CONSOLE_ENABLE = no
KEY_OVERRIDE_ENABLE = no
CAPS_WORD_ENABLE = yes
LEADER_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes
